### ISSUE TITLE
是否可以增加双开应用选择设置

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Unify-Sign#1]
部分应用有双开的需求，如淘宝京东什么的，是否能在可视化设置里增加相关设置？
![738de3787d5c8db6c0ab01bc6faca6d](https://user-images.githubusercontent.com/58156677/124848595-c5853d80-dfcf-11eb-8429-b7b2ed6f5fb9.jpg)

**Comment by TonyJiangWJ** [comment]
这个不太好实现，因为不同品牌手机的选择框不太一样 适配起来比较麻烦

**Comment by williamglasgow** [comment]
增加一个点击开关？然后用户自己设置点击坐标

**Comment by TonyJiangWJ** [comment]
那不如自己改代码算了 吃力不讨好
