### ISSUE TITLE
建议增加下每个任务的手动执行按钮

### ISSUE THREAD

**Issue by xuanyuanaosheng** [TonyJiangWJ/Unify-Sign#10]
请问是否可以在配置管理里面的签到设置里面增加一个立即执行的按钮？这样方便每天闲了的时候手动执行？

**Comment by TonyJiangWJ** [comment]
我后面考虑一下，你这种可以自己在执行计划里面复制新任务进行执行。或者自己根据测试脚本创建自己的独立js

**Comment by xuanyuanaosheng** [comment]
感谢~
