### ISSUE TITLE
请教大佬，这个程序电脑上运行需要做啥改动吗？

### ISSUE THREAD

**Issue by smallfish01** [TonyJiangWJ/Unify-Sign#7]
想在Ubuntu 虚拟机上运行，不知道还要做什么配置才能运行您的这些代码？

**Comment by TonyJiangWJ** [comment]
。。。AutoJS是安卓上跑的程序 放弃吧 要么你装个安卓模拟器 何必呢 找青龙面板吧

**Comment by smallfish01** [comment]
> 。。。AutoJS是安卓上跑的程序 放弃吧 要么你装个安卓模拟器 何必呢 找青龙面板吧

非常感谢您的及时回复，刚没注意看，还以为可以在虚拟机上运行。
不知道有没有可以在Linux虚拟机上运行的自动签到代码？找了一些貌似都不太好。

再次感谢。

**Comment by TonyJiangWJ** [comment]
具体的我也不知道 不玩 就知道有个叫青龙面板的 具体的你自己去找吧

**Comment by smallfish01** [comment]
> 具体的我也不知道 不玩 就知道有个叫青龙面板的 具体的你自己去找吧

非常感谢，祝您元旦快乐！
