### ISSUE TITLE
希望能创建一个 telegram的群

### ISSUE THREAD

**Issue by xuanyuanaosheng** [TonyJiangWJ/Unify-Sign#8]

**Comment by TonyJiangWJ** [comment]
诈骗小飞机警告。以后搞一个 没用它的习惯

**Comment by xuanyuanaosheng** [comment]
@TonyJiangWJ   感谢回复，楼主自己创建即可~    也给大家一个交流的地方。

**Comment by xuanyuanaosheng** [comment]
再次感谢大佬的分享

**Comment by TonyJiangWJ** [comment]
单纯为了交流进QQ群就行了，玩这个用小飞机的没多少人

**Comment by xuanyuanaosheng** [comment]
@TonyJiangWJ 没找到QQ群，方便的话，发一下？

**Comment by TonyJiangWJ** [comment]
https://github.com/TonyJiangWJ/Ant-Forest/blob/88dde1eda7500a30f923a90bef995f7bb0fbf23e/config.js#L239-L240

**Comment by xuanyuanaosheng** [comment]
再次表示感谢~~
