### ISSUE TITLE
请问是否有适配下面项目的打算？

### ISSUE THREAD

**Issue by xuanyuanaosheng** [TonyJiangWJ/Unify-Sign#9]
https://github.com/SuperMonster003/AutoJs6
https://github.com/kkevsekk1/AutoX

则两个项目在github上更新比较活跃。我刚测试，没办法在AutoJs6 上直接运行，报错如下：

![image](https://github.com/TonyJiangWJ/Unify-Sign/assets/4197714/27aaee7c-9b2d-4022-be73-1a45d7558d2a)

**Comment by TonyJiangWJ** [comment]
没有这方面的计划

**Comment by finvv** [comment]
同求，现在用这两个项目的人很多，我就用autoxjs，也是报错，(ㄒoㄒ)

**Comment by TonyJiangWJ** [comment]
脚本内OCR以及后续Yolo识别等功能将强依赖于魔改版，无法适配其他版本。
